# -*- coding: utf-8 -*-
"""Bản sao của Project2_baitoan1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mri2hSJa41KzTga1ZVy9DAS-o8gNXADg
"""

!pip install pyvi
!pip install langdetect
!pip install wordcloud
!pip install gensim

from google.colab import drive
drive.mount('/content/drive')

import re
import warnings
warnings.filterwarnings('ignore')

import time
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from langdetect import detect
from wordcloud import WordCloud
from sklearn.decomposition import TruncatedSVD
from gensim import corpora, models, similarities
from pyvi.ViTokenizer import tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

"""# Read and overview data"""

data = pd.read_excel('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/data_motobikes.xlsx')
data.head(3)

data.info()

data['title'] = data['Tiêu đề']
data['description'] = data['Mô tả chi tiết']
data = data[['id', 'title', 'description', 'Dòng xe']]

data.head(3)

for desc in data['description']:
  print(desc)

for i in range(20):
  print(f"{i}/ {data['description'][i]}")

data.info()

data.dropna(inplace=True)

data.duplicated().any()

"""# Preprocessing data"""

def load_dict(path:str):
  dict_results = {}
  with open(path, 'r') as f:
    file = f.read()
  file = file.split('\n')
  for line in file:
    v, k = line.split('\t')
    dict_results[v] = k
  return dict_results

def load_list(path:str):
  with open(path, 'r') as f:
    file = f.read()
  file = file.split('\n')
  return (file)

dict_teencode = load_dict('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/files/teencode.txt')
lst_wrong_txt = load_list('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/files/wrong-word.txt')
lst_stopwords = load_list('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/files/vietnamese-stopwords.txt')
dict_emoji = load_dict('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/files/emojicon.txt')
dict_translate = load_dict('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/files/english-vnmese.txt')
lst_stopwords.append('xe')

# Compile regex
url_regex = re.compile(r'http\S+|www\S+')
# Regex này sẽ xóa số và các dấu câu phổ biến
punct_regex_v2 = r'[!"#$%&\'()*+,/:;<=>?@\[\]\\^`{|}~]'

def preprocess_text(description: str):

    if not isinstance(description, str):
        return "" # Xử lý các giá trị không phải là chuỗi (ví dụ: NaN)

    # Bước 1: Chuẩn hóa cơ bản
    text = description.lower() # Chuyển về chữ thường
    text = re.sub(url_regex, ' ', text) # Xóa URLs

    # Bước 2: Dịch Tiếng Anh (Tùy chọn, có thể giữ)
    # for eng, vie in dict_translate.items():
    #    text = re.sub(r'\b' + re.escape(eng) + r'\b', f' {vie} ', text)

    # Bước 3: Thay thế Emojis
    for emoji, meaning in dict_emoji.items():
        text = text.replace(emoji, f' {meaning} ')

    # Bước 4: Thay thế Teencode
    for code, meaning in dict_teencode.items():
        text = re.sub(r'\b' + re.escape(code) + r'\b', f' {meaning} ', text)

    # Bước 5: Tokenization tiếng Việt
    text = tokenize(text)

    # Bước 6: Gỡ bỏ nhiễu (Chỉ dấu câu, GIỮ LẠI SỐ)
    text = re.sub(punct_regex_v2, ' ', text) # Dùng regex V2

    # Bước 7: Lọc Stopwords
    # CHỈ LỌC 'set_stopwords', không lọc 'wrong-word.txt'
    tokens = text.split()

    cleaned_tokens = []
    for token in tokens:
        # Kiểm tra token không có trong set stopwords
        # Vẫn giữ 'len(token) > 1' để lọc các từ rác 1 ký tự (như 'a', 'b', 'c'...)
        if token not in lst_stopwords and len(token) > 1:
            cleaned_tokens.append(token)

    # Bước 8: Nối lại và chuẩn hóa
    final_text = ' '.join(cleaned_tokens)


    # Dọn dẹp khoảng trắng
    final_text = re.sub(r'\s+', ' ', final_text).strip()

    return final_text

test_string = "Mình đi xuất cảnh định cư nên cần bán chiếc xe honda LEAD 2020 BSTP xe nhà ít đi.bảo dưỡng đầy đủ nên xe còn rất mới.zin từ trong ra ngoài.nước sơn zin ko dặm tút.máy móc zin êm.chạy rất mạnh và nhẹ ga.xe này mua về là đi thôi.ko phải làm gì hết.xe sài smakey.còn đủ 2 kính.xe màu đỏ đô.tới xem xe phát hiện ra chổ nào ko zin hoặc dậm tút tặng luôn xe.mình là nguoi dùng bán.chứ ko phải cò lái.giấy tờ hợp pháp mua bán ra phòng công chứng,công chứng sang tên luôn."

cleaned = preprocess_text(test_string)
print(f"Original: {test_string}")
print(f"Cleaned: {cleaned}")

data['description_cleaned'] = data['description'].apply(preprocess_text)
data['title_cleaned'] = data['title'].apply(preprocess_text)

for desc_raw, desc_cleaned in zip(data['description'][:2], data['description_cleaned'][:2]):
  print(60*'=')
  print(f'*Description Before_clean: {desc_raw} \n')
  print(f'*Description After_clean: {desc_cleaned} \n')

for title_raw, title_cleaned in zip(data['title'][:2], data['title_cleaned'][:2]):
  print(60*'=')
  print(f'*title Before_clean: {title_raw} \n')
  print(f'*title After_clean: {title_cleaned} \n')

"""# Visualize data"""

content = ' '.join(data['description_cleaned'])

wc = WordCloud().generate(content)
plt.imshow(wc)
plt.axis('off')
plt.title('WordCloud for Description')
plt.show()

content = ' '.join(data['title_cleaned'])

wc = WordCloud().generate(content)
plt.imshow(wc)
plt.axis('off')
plt.title('WordCloud for Title')
plt.show()

data['content'] = data['description_cleaned'] + ' ' + data['title_cleaned']

word_counter = CountVectorizer()
word_counts_matrix = word_counter.fit_transform(data['content'])

word_frequencies = pd.DataFrame({
    'term': word_counter.get_feature_names_out(),
    'frequency': word_counts_matrix.sum(axis=0).getA1()
})

top_words = word_frequencies.sort_values(by='frequency', ascending=False).head(20)

plt.figure(figsize=(12, 8))
sns.barplot(x='frequency', y='term', data=top_words, palette='viridis')
plt.title('Top 20 từ có tần suất cao nhất', fontsize=16)
plt.xlabel('Tần suất', fontsize=12)
plt.ylabel('Từ', fontsize=12)
plt.show()

"""# Recommendation using cosine similarity"""

tfidf_vectorizer = TfidfVectorizer(
    min_df=2,      # Bỏ qua các từ xuất hiện ít hơn 5 lần
    max_df=0.8,    # Bỏ qua các từ xuất hiện trong hơn 80% tài liệu (từ quá chung)
    ngram_range=(1, 2) # Xem xét cả từ đơn (unigram) và cụm 2 từ (bigram)
)

print("Bắt đầu huấn luyện Model 1")
start_time_model_1 = time.time()

tfidf_matrix = tfidf_vectorizer.fit_transform(data['content'])

cosine_score = cosine_similarity(tfidf_matrix)

end_time_model_1 = time.time()
train_time_model_1 = end_time_model_1 - start_time_model_1
print(f"--- Hoàn thành Model 1 (Sklearn) ---")
print(f"Shape của TF-IDF matrix: {tfidf_matrix.shape}")
print(f"Thời gian huấn luyện: {train_time_model_1:.4f} giây")
df_cosine_score = pd.DataFrame(cosine_score)

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf_vectorizer, f)

data

data.to_csv('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/data_motobikes_cleaned_text.csv', index=False)

def choose_best_k_recommend(k:int, df_cosine_score:pd.DataFrame, id:int):
  df_recommend = df_cosine_score[[id-1]]
  lst_best_recommend = df_recommend.sort_values(by = id - 1, ascending = False).index

  lst_best_recommend = list(lst_best_recommend)

  return list(lst_best_recommend)[:k]

best_k_indexes = choose_best_k_recommend(15, df_cosine_score, 3)
best_k_indexes

# def recommend(data, df_cosine_score, user_id, k):
#   best_k_indexes = choose_best_k_recommend(k, df_cosine_score, user_id)
#   print(f'Content of user id {user_id}: \n')
#   print(data.loc[user_id, 'content'])
#   print(50*'=')
#   print(f'Top {k} that should recommend to user id {user_id}')
#   return data.loc[best_k_indexes].iloc[1:]

# df_result = recommend(data, df_cosine_score, 2, 10)
# df_result

def recommend(data, df_cosine_score, id, k, verboose = True):
    best_k_indexes = choose_best_k_recommend(k, df_cosine_score, id)

    if verboose:
      print(f'Content of id {id}: \n')
      print(data.loc[id - 1, 'content'])
      print(50*'=')

      print(f'Top {k} that should recommend to user id {id}')

    # Lấy điểm cosine tương ứng
    cosine_scores = df_cosine_score.loc[id - 1, best_k_indexes]

    # Tạo DataFrame kết quả kèm score
    result = data.loc[best_k_indexes].copy()
    result['cosine_score'] = cosine_scores.values

    return result.iloc[1:]   # bỏ user chính nếu choose_best_k có chứa self

df_result = recommend(data, df_cosine_score, 3, 10)
df_result

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/xe_cosine_sim.pkl', 'wb') as f:
    pickle.dump(cosine_score, f)

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/xe_cosine_sim.pkl', 'rb') as f:
    cosine_sim_new = pickle.load(f)

df_cosine_new = pd.DataFrame(cosine_sim_new)

df_result = recommend(data, df_cosine_new, 3, 10)
df_result

"""## Input text from user and recommend (feature)"""

data.shape

# # Ngoài dataset
# def out_recommend_motorbike(text = '', top_k=5, data = None):
#   print("Input:", text)
#   text = preprocess_text(text)
#   df_sample = pd.DataFrame({
#       'content' : [text]
#   })
#   text_feat = vectorizer.transform(df_sample['content'])
#   cosine_score = cosine_similarity(tfidf_matrix, text_feat)
#   df_result = pd.DataFrame(cosine_score)
#   best_indexes = list(df_result.sort_values(by = 0, ascending = False).index)

#   best_k_index = best_indexes[:top_k]
#   return data.iloc[best_k_indexes, :]

# out_recommend_motorbike("T cần mua 1 chiếc vespa### nguyên zin 💖", 5, data)

# Ngoài dataset
def out_recommend_motorbike(text='', top_k=5, data=None):
    print("Input:", text)

    # Preprocess
    text = preprocess_text(text)
    df_sample = pd.DataFrame({'content': [text]})

    # Transform text
    text_feat = tfidf_vectorizer.transform(df_sample['content'])

    # Compute cosine similarity
    cosine_score = cosine_similarity(tfidf_matrix, text_feat).flatten()

    # Convert to DataFrame
    df_result = pd.DataFrame({
        "cosine_score": cosine_score
    })

    # Sort by cosine score
    best_indexes = df_result.sort_values(by="cosine_score", ascending=False).index
    best_k_indexes = best_indexes[:top_k]

    # Extract rows
    result = data.iloc[best_k_indexes, :].copy()

    # Thêm cột cosine score tương ứng
    result["cosine_score"] = df_result.loc[best_k_indexes, "cosine_score"].values

    return result
out_recommend_motorbike("T cần mua 1 chiếc vespa### nguyên zin 💖", 5, data)

content_gensism = [[w for w in text.split()] for text in data['content']]

content_gensism[:1]

i = 1
print(data['content'][i])
print("=========")
content_gensism[i]

#Remove leading '_'
cleaned_content_genism = [
    [w.lstrip('_') for w in tokens]
    for tokens in content_gensism
]

cleaned_content_genism[1]

dictionary = corpora.Dictionary(cleaned_content_genism)

dictionary.token2id

feature_cnt = len(dictionary.token2id)
feature_cnt

corpus = [dictionary.doc2bow(text) for text in cleaned_content_genism]
corpus[1]

print("Bắt đầu huấn luyện Model 2")
start_time_model_2 = time.time()

tfidf = models.TfidfModel(corpus)

index = similarities.SparseMatrixSimilarity(tfidf[corpus],
                                            num_features = feature_cnt)
similarities_df = pd.DataFrame(index)

end_time_model_2 = time.time()
train_time_model_2 = end_time_model_2 - start_time_model_2
print(f"--- Hoàn thành Model 2 (Gensim) ---")
print(f"Thời gian huấn luyện: {train_time_model_2:.4f} giây")

id = 0
customer_search = cleaned_content_genism[id]
top5 = similarities_df.loc[id].drop(id, errors='ignore').nlargest(5)
top5

# Nội trong dataset.
def in_recommend_motorbike(i, top_k=5, verboose = True):
  text = data['content'][i-1]
  if verboose:
    print("Input:", text)
  top_similarity = similarities_df.loc[i-1].drop(i-1, errors='ignore').nlargest(top_k)
  if verboose:
    print("Top similarity", top_similarity)
  return data['content'].iloc[top_similarity.index.tolist()]

in_recommend_motorbike(1)

# Ngoài dataset
def out_recommend_motorbike(text, top_k=5):
  print("Input:", text)
  # 1. Đọc text và preprocess
  text = preprocess_text(text)
  tokens = text.split()
  # 2. Xây dựng similarities
  bow_vec = dictionary.doc2bow(tokens)
  tfidf_vec = tfidf[bow_vec]
  sims = index[tfidf_vec]
  # 3. Đưa recommendations
  top_idx = np.argsort(-sims)[:top_k]
  return data['content'].iloc[top_idx]

user_search = 'Wave màu trắng'
out_recommend_motorbike(user_search)