# -*- coding: utf-8 -*-
"""Project_2_baitoan2_tradition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ex04By6N4eK856PsqidO7DWonkMHed3u
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install kmodes
!pip install gower

import re
import time
import warnings
warnings.filterwarnings('ignore')
import pickle
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import silhouette_samples
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score, adjusted_rand_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest
from kmodes.kprototypes import KPrototypes
import gower

"""# 1. Read and overview data

Here we use the encoded dataset from project_1 which was preprocessed and here because of the target of cluster by price so we do not need text here like problem 1
"""

data = pd.read_csv('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/encoded_data_motobikes.csv')

data.head(5)

"""Because data has many outliers and we want to apply K_means so we need scaler like RobustScaler"""

data.info()

"""# 2. Kmeans Model"""

# Import and scale data
X = data.values
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# Detect and remove outliers
outlier_detector = IsolationForest(contamination=0.1, random_state=42)
outlier_labels = outlier_detector.fit_predict(X_scaled)

# Filter both scaled data and original dataframe
X_scaled_clean = X_scaled[outlier_labels == 1]  #
data_clean = data[outlier_labels == 1]



"""### Silhouette Analysis"""

# Clustering analysis
silhouete_results = []
sse_results = []
k_clusters = list(range(2, 20))

total_start = time.perf_counter()

for k in k_clusters:
    iter_start = time.perf_counter()

    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = model.fit_predict(X_scaled_clean)

    # Silhouette score - use cleaned data consistently
    score = silhouette_score(X_scaled_clean, labels)
    silhouete_results.append(score)

    # SSE (WCSS / inertia)
    sse = model.inertia_
    sse_results.append(sse)

    iter_end = time.perf_counter()
    iter_time = iter_end - iter_start

    print(f"k={k}: Silhouette = {score:.4f}, WSSSE = {sse:.2f}, Time = {iter_time:.2f} sec")

total_end = time.perf_counter()
total_time = total_end - total_start

print("\n" + "="*60)
print(f"Total runtime for k=2 to 19: {total_time:.2f} sec")
print("="*60)

# Check k=2 cluster distribution
model_k2 = KMeans(n_clusters=2, random_state=42, n_init=10)
labels_k2 = model_k2.fit_predict(X_scaled_clean)

print("K=2 Cluster Sizes:")
for i in range(2):
    cluster_silhouette = silhouette_samples(X_scaled_clean, labels_k2)[labels_k2 == i].mean()
    cluster_size = (labels_k2 == i).sum()
    print(f"Cluster {i}: Size = {cluster_size}, Avg Silhouette = {cluster_silhouette:.4f}")

# Check k=4 (also has high score)
model_k4 = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_k4 = model_k4.fit_predict(X_scaled_clean)

print("\nK=3 Cluster Sizes:")
for i in range(3):
    cluster_silhouette = silhouette_samples(X_scaled_clean, labels_k4)[labels_k4 == i].mean()
    cluster_size = (labels_k4 == i).sum()
    print(f"Cluster {i}: Size = {cluster_size}, Avg Silhouette = {cluster_silhouette:.4f}")

centroids_scaled = model_k4.cluster_centers_
centroids = scaler.inverse_transform(centroids_scaled)

centroid_df = pd.DataFrame(
    centroids,
    columns=data.columns  # your original feature names
)
print(centroid_df)

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (16, 12)

# Create figure with subplots
fig = plt.figure(figsize=(18, 12))

# ============= K=2 Visualizations =============
# 1. Cluster sizes bar chart (K=2)
ax1 = plt.subplot(3, 3, 1)
k2_sizes = [np.sum(labels_k2 == i) for i in range(2)]
colors_k2 = ['#FF6B6B', '#4ECDC4']
bars1 = ax1.bar(range(2), k2_sizes, color=colors_k2, alpha=0.7, edgecolor='black')
ax1.set_xlabel('Cluster', fontsize=12, fontweight='bold')
ax1.set_ylabel('Number of Samples', fontsize=12, fontweight='bold')
ax1.set_title('K=2: Cluster Sizes', fontsize=14, fontweight='bold')
ax1.set_xticks(range(2))
for i, bar in enumerate(bars1):
    height = bar.get_height()
    ax1.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(height)}\n({height/len(labels_k2)*100:.1f}%)',
             ha='center', va='bottom', fontsize=10, fontweight='bold')

# 2. Silhouette scores bar chart (K=2)
ax2 = plt.subplot(3, 3, 2)
k2_silhouettes = [silhouette_samples(X_scaled_clean, labels_k2)[labels_k2 == i].mean() for i in range(2)]
bars2 = ax2.bar(range(2), k2_silhouettes, color=colors_k2, alpha=0.7, edgecolor='black')
ax2.set_xlabel('Cluster', fontsize=12, fontweight='bold')
ax2.set_ylabel('Average Silhouette Score', fontsize=12, fontweight='bold')
ax2.set_title('K=2: Silhouette Scores by Cluster', fontsize=14, fontweight='bold')
ax2.set_xticks(range(2))
ax2.set_ylim(0, 1)
ax2.axhline(y=0.5, color='red', linestyle='--', alpha=0.5, label='Threshold 0.5')
ax2.legend()
for i, bar in enumerate(bars2):
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.3f}',
             ha='center', va='bottom', fontsize=10, fontweight='bold')

# 3. PCA scatter plot (K=2)
ax3 = plt.subplot(3, 3, 3)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled_clean)
for i in range(2):
    mask = labels_k2 == i
    ax3.scatter(X_pca[mask, 0], X_pca[mask, 1],
               c=colors_k2[i], label=f'Cluster {i} (n={k2_sizes[i]})',
               alpha=0.6, s=30, edgecolors='black', linewidth=0.5)
ax3.set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)', fontsize=11, fontweight='bold')
ax3.set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)', fontsize=11, fontweight='bold')
ax3.set_title('K=2: PCA Visualization', fontsize=14, fontweight='bold')
ax3.legend(loc='best')
ax3.grid(True, alpha=0.3)

# ============= K=3 Visualizations =============
# 4. Cluster sizes bar chart (K=3)
ax4 = plt.subplot(3, 3, 4)
k3_sizes = [np.sum(labels_k4 == i) for i in range(3)]
colors_k3 = ['#FF6B6B', '#4ECDC4', '#95E1D3']
bars3 = ax4.bar(range(3), k3_sizes, color=colors_k3, alpha=0.7, edgecolor='black')
ax4.set_xlabel('Cluster', fontsize=12, fontweight='bold')
ax4.set_ylabel('Number of Samples', fontsize=12, fontweight='bold')
ax4.set_title('K=3: Cluster Sizes', fontsize=14, fontweight='bold')
ax4.set_xticks(range(3))
for i, bar in enumerate(bars3):
    height = bar.get_height()
    ax4.text(bar.get_x() + bar.get_width()/2., height,
             f'{int(height)}\n({height/len(labels_k4)*100:.1f}%)',
             ha='center', va='bottom', fontsize=10, fontweight='bold')

# 5. Silhouette scores bar chart (K=3)
ax5 = plt.subplot(3, 3, 5)
k3_silhouettes = [silhouette_samples(X_scaled_clean, labels_k4)[labels_k4 == i].mean() for i in range(3)]
bars4 = ax5.bar(range(3), k3_silhouettes, color=colors_k3, alpha=0.7, edgecolor='black')
ax5.set_xlabel('Cluster', fontsize=12, fontweight='bold')
ax5.set_ylabel('Average Silhouette Score', fontsize=12, fontweight='bold')
ax5.set_title('K=3: Silhouette Scores by Cluster', fontsize=14, fontweight='bold')
ax5.set_xticks(range(3))
ax5.set_ylim(0, 1)
ax5.axhline(y=0.5, color='red', linestyle='--', alpha=0.5, label='Threshold 0.5')
ax5.legend()
for i, bar in enumerate(bars4):
    height = bar.get_height()
    ax5.text(bar.get_x() + bar.get_width()/2., height,
             f'{height:.3f}',
             ha='center', va='bottom', fontsize=10, fontweight='bold')

# 6. PCA scatter plot (K=3)
ax6 = plt.subplot(3, 3, 6)
for i in range(3):
    mask = labels_k4 == i
    ax6.scatter(X_pca[mask, 0], X_pca[mask, 1],
               c=colors_k3[i], label=f'Cluster {i} (n={k3_sizes[i]})',
               alpha=0.6, s=30, edgecolors='black', linewidth=0.5)
ax6.set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)', fontsize=11, fontweight='bold')
ax6.set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)', fontsize=11, fontweight='bold')
ax6.set_title('K=3: PCA Visualization', fontsize=14, fontweight='bold')
ax6.legend(loc='best')
ax6.grid(True, alpha=0.3)

# ============= Comparison Charts =============
# 7. Pie chart comparison (K=2)
ax7 = plt.subplot(3, 3, 7)
ax7.pie(k2_sizes, labels=[f'Cluster {i}\n({s} cars)' for i, s in enumerate(k2_sizes)],
        colors=colors_k2, autopct='%1.1f%%', startangle=90,
        textprops={'fontsize': 11, 'fontweight': 'bold'})
ax7.set_title('K=2: Cluster Distribution', fontsize=14, fontweight='bold')

# 8. Pie chart comparison (K=3)
ax8 = plt.subplot(3, 3, 8)
ax8.pie(k3_sizes, labels=[f'Cluster {i}\n({s} cars)' for i, s in enumerate(k3_sizes)],
        colors=colors_k3, autopct='%1.1f%%', startangle=90,
        textprops={'fontsize': 10, 'fontweight': 'bold'})
ax8.set_title('K=3: Cluster Distribution', fontsize=14, fontweight='bold')

# 9. Overall comparison table
ax9 = plt.subplot(3, 3, 9)
ax9.axis('off')

# Create comparison data
comparison_data = [
    ['Metric', 'K=2', 'K=3'],
    ['Avg Silhouette', f'{np.mean(k2_silhouettes):.3f}', f'{np.mean(k3_silhouettes):.3f}'],
    ['Min Silhouette', f'{np.min(k2_silhouettes):.3f}', f'{np.min(k3_silhouettes):.3f}'],
    ['Max Silhouette', f'{np.max(k2_silhouettes):.3f}', f'{np.max(k3_silhouettes):.3f}'],
    ['Largest Cluster %', f'{max(k2_sizes)/sum(k2_sizes)*100:.1f}%', f'{max(k3_sizes)/sum(k3_sizes)*100:.1f}%'],
    ['Smallest Cluster %', f'{min(k2_sizes)/sum(k2_sizes)*100:.1f}%', f'{min(k3_sizes)/sum(k3_sizes)*100:.1f}%'],
]

table = ax9.table(cellText=comparison_data, cellLoc='center', loc='center',
                  colWidths=[0.4, 0.3, 0.3])
table.auto_set_font_size(False)
table.set_fontsize(11)
table.scale(1, 2.5)

# Style header row
for i in range(3):
    table[(0, i)].set_facecolor('#34495e')
    table[(0, i)].set_text_props(weight='bold', color='white')

# Alternate row colors
for i in range(1, len(comparison_data)):
    for j in range(3):
        if i % 2 == 0:
            table[(i, j)].set_facecolor('#ecf0f1')

ax9.set_title('K=2 vs K=3 Comparison', fontsize=14, fontweight='bold', pad=20)

plt.suptitle('KMeans Clustering Analysis: K=2 vs K=3',
             fontsize=18, fontweight='bold', y=0.995)
plt.tight_layout(rect=[0, 0, 1, 0.99])
plt.show()

"""### Elbow method"""

# Plot elbow curve for k = 3
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(k_clusters, sse_results, 'bo-')
plt.xlabel('Number of clusters (k)')
plt.ylabel('SSE (Within-Cluster Sum of Squares)')
plt.title('Elbow Method')
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(k_clusters, silhouete_results, 'ro-')
plt.xlabel('Number of clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Analysis')
plt.axhline(y=0.70, color='g', linestyle='--', label='Your k=3 score')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

# Check individual cluster quality for k=3
model_best = KMeans(n_clusters=3, random_state=42, n_init=10)
labels_best = model_best.fit_predict(X_scaled_clean)

from sklearn.metrics import silhouette_samples
silhouette_vals = silhouette_samples(X_scaled_clean, labels_best)

for i in range(3):
    cluster_silhouette = silhouette_vals[labels_best == i].mean()
    cluster_size = (labels_best == i).sum()
    print(f"Cluster {i}: Avg Silhouette = {cluster_silhouette:.4f}, Size = {cluster_size}")

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/kmeans.pkl', 'wb') as f:
 pickle.dump(model_best, f)

"""# KProttotypes Model"""

data.info()

# 1. Identify categorical column indices
categorical_cols = [0,1,2,3]

# 2. Convert dataframe to numpy
X = data.to_numpy()

# 3. Fit K-Prototypes
kproto = KPrototypes(n_clusters=3, init='Huang', random_state=42)
labels = kproto.fit_predict(X, categorical=categorical_cols)

# 4. Cluster sizes
print(np.bincount(labels))

numeric_cols = ["Khoảng giá min", "Khoảng giá max", "Năm đăng ký", "Số Km đã đi", "Giá"]
data_clustered = data.copy()
data_clustered["cluster"] = labels
print(
    data_clustered
    .groupby("cluster")[numeric_cols]
    .mean()
    .round(2)
)

cat_cols = ["Thương hiệu", "Dòng xe", "Loại xe", "Xuất xứ"]
num_cols = ["Khoảng giá min", "Khoảng giá max", "Năm đăng ký", "Số Km đã đi", "Giá"]

X_cat = data[cat_cols].to_numpy()
X_num = data[num_cols].to_numpy()

scaler = StandardScaler()
X_num_scaled = scaler.fit_transform(X_num)

X_combined = np.concatenate([X_cat, X_num_scaled], axis=1)
categorical_idx = [0,1,2,3]

kproto = KPrototypes(n_clusters=3, init='Huang', random_state=42)
labels = kproto.fit_predict(X_combined, categorical=categorical_idx)


pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_num_scaled)

fig, ax = plt.subplots(figsize=(10,8))

unique_labels = np.unique(labels)
colors = sns.color_palette("husl", len(unique_labels))

for i, label in enumerate(unique_labels):
    mask = labels == label
    ax.scatter(
        X_pca[mask, 0],
        X_pca[mask, 1],
        c=[colors[i]],
        label=f"Cluster {label}",
        s=50,
        alpha=0.7
    )

ax.set_title("K-Prototypes Clustering Visualized via PCA (Numeric Features Only)", fontsize=16, fontweight="bold")
ax.set_xlabel("PC1", fontsize=12)
ax.set_ylabel("PC2", fontsize=12)

ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/scaler_standard_kproto.pkl', 'wb') as f:
        pickle.dump(scaler, f)

data_clustered = data.copy()
data_clustered["cluster"] = labels

numeric_cols = ["Khoảng giá min", "Khoảng giá max", "Năm đăng ký", "Số Km đã đi", "Giá"]
cat_cols = [col for i, col in enumerate(data.columns) if i in categorical_cols]

# Numeric summary
print("=== Numeric features by cluster ===")
print(
    data_clustered
    .groupby("cluster")[numeric_cols]
    .mean()
    .round(2)
)

# Categorical summary: mode in each cluster
def mode_series(s):
    return s.mode().iloc[0] if not s.mode().empty else None

print("\n=== Categorical features by cluster ===")
print(
    data_clustered
    .groupby("cluster")[cat_cols]
    .agg(mode_series)
)

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/kproto.pkl', 'wb') as f:
 pickle.dump(kproto, f)

"""# Gaussian Mixture

## Using Silhouete score
"""

# Import and scale data
X = data.values
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)

# Detect and remove outliers
outlier_detector = IsolationForest(contamination=0.1, random_state=42)
outlier_labels = outlier_detector.fit_predict(X_scaled)

# Filter both scaled data and original dataframe
X_scaled_clean = X_scaled[outlier_labels == 1]  #
data_clean = data[outlier_labels == 1]

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/scaler_robust.pkl', 'wb') as f:
    pickle.dump(scaler, f)

import time

gmm_silhouete_results = []
gmm_sse_results = []
k_values = list(range(2, 20))

total_start = time.perf_counter()

for k in k_values:
    iter_start = time.perf_counter()

    gmm = GaussianMixture(n_components=k, random_state=42)
    gmm_labels = gmm.fit_predict(X_scaled)

    # --- Silhouette ---
    sil_score = silhouette_score(X_scaled, gmm_labels)
    gmm_silhouete_results.append(sil_score)

    # --- SSE (manual) ---
    means = gmm.means_
    sse = np.sum([np.sum((X[gmm_labels == j] - means[j])**2) for j in range(k)])
    gmm_sse_results.append(sse)

    iter_end = time.perf_counter()

    print(f"k={k}: Silhouette={sil_score:.4f}, SSE={sse:.2f}, Time={iter_end - iter_start:.2f}s")

total_end = time.perf_counter()
print("\nTotal runtime:", round(total_end - total_start, 2), "seconds")

# Best k
best_k = k_values[np.argmax(gmm_silhouete_results)]
print(f"\nOptimal k from GMM silhouette analysis: {best_k}")

# Compare K-Means vs GMM silhouette scores
plt.figure(figsize=(10, 6))
plt.plot(k_clusters, silhouete_results, 'bo-', linewidth=2, label='K-Means', markersize=8)
plt.plot(k_values, gmm_silhouete_results, 'ro-', linewidth=2, label='GMM', markersize=8)
plt.xlabel('Number of Clusters (k)', fontsize=12)
plt.ylabel('Silhouette Score', fontsize=12)
plt.title('K-Means vs GMM Silhouette Comparison', fontsize=16, fontweight='bold')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

gmm_optimal = GaussianMixture(n_components = 4, random_state = 42)
gmm_optimal.fit(X)

print(f'GMM results')
print(f' Converged: {gmm_optimal.converged_}')
print(f' Num of iterations: {gmm_optimal.n_iter_}')
print(f' Log-likelihood : {gmm_optimal.score(X) :.2f}')
print(f' AIC: {gmm_optimal.aic(X):.2f}')
print(f' AIC: {gmm_optimal.bic(X):.2f}')

# Display GMM parameters
print("\nGMM Parameters:")
print(f"   Component weights: {gmm_optimal.weights_}")
print(f"   Component means:")
for i, mean in enumerate(gmm_optimal.means_):
    print(f"      Component {i}: [{mean[0]:.3f}, {mean[1]:.3f}, {mean[2]:.3f}, {mean[3]:.3f}]")

print(f"   Component covariances shape:{gmm_optimal.covariances_.shape}")

with open('/content/drive/MyDrive/DL07_K308_PhamNamAn_CaoThanhBang/Project_2/gmm.pkl', 'wb') as f:
 pickle.dump(gmm_optimal, f)

